name              "symfony"
maintainer        "lelivrescolaire.fr"
maintainer_email  ""
license           "MIT"
description       "Set of recipes to manage symfony applications deployment"
version           "1.0.0"